# Generated by Django 5.2.1 on 2025-09-10 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='new_sellers',
        ),
        migrations.AlterField(
            model_name='shop',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='new_shops', through='main.ShopUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
