# Generated by Django 5.2.5 on 2025-09-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cupon_used_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='used_on',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
