# Generated by Django 5.2.1 on 2025-09-10 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shop_new_sellers_alter_shop_sellers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='old_sellers',
            field=models.ManyToManyField(related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
