# Generated by Django 5.2.1 on 2025-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_old_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
