# Generated by Django 5.2.1 on 2025-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_customers_order_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payed",
            field=models.BooleanField(default=False),
        ),
    ]
