# Generated by Django 5.2.1 on 2025-05-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_order_payed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
