# Generated by Django 5.2.5 on 2025-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cupon_used_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.FloatField(default=0),
        ),
    ]
