# Generated by Django 5.2.1 on 2025-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
