# Generated by Django 5.2.5 on 2025-09-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderitem_price_at_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='used_on',
        ),
        migrations.AddField(
            model_name='order',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cupon'),
        ),
    ]
