# Generated by Django 5.2.1 on 2025-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_needs_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
