# Generated by Django 5.2.5 on 2025-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
